-- Crear los temas (si no existen)
insert into temas (nombre) values ('Inclinación de Ángulos y Conicidades') on conflict (nombre) do nothing;
insert into temas (nombre) values ('Tipos y Cálculo de Roscas') on conflict (nombre) do nothing;
insert into temas (nombre) values ('Cálculo de RPM y Velocidades de Corte') on conflict (nombre) do nothing;
insert into temas (nombre) values ('Conversión de Unidades y Metrología') on conflict (nombre) do nothing;

-- Insertar preguntas del Examen de Matemática Aplicada al Mecanizado Industrial
do $$
declare
  tema_0 uuid;
  tema_1 uuid;
  tema_2 uuid;
  tema_3 uuid;
begin
  select id into tema_0 from temas where nombre = 'Inclinación de Ángulos y Conicidades';
  select id into tema_1 from temas where nombre = 'Tipos y Cálculo de Roscas';
  select id into tema_2 from temas where nombre = 'Cálculo de RPM y Velocidades de Corte';
  select id into tema_3 from temas where nombre = 'Conversión de Unidades y Metrología';
  insert into banco_preguntas (tema_id, tipo, texto, opts, correcto) values (tema_0, 'mc', 'Se requiere tornear un cono en un torno convencional utilizando el método de inclinación del carro orientable. Si el diámetro mayor es D = 50 mm, el diámetro menor es d = 40 mm y la longitud del cono es L = 60 mm, ¿cuál es el ángulo de inclinación del carro (alfa)?', '["alfa ≈ 9.46°", "alfa ≈ 4.76°", "alfa ≈ 5.71°", "alfa ≈ 2.38°"]'::jsonb, 1);
  insert into banco_preguntas (tema_id, tipo, texto, opts, correcto) values (tema_0, 'mc', 'Se desea maquinar una conicidad sobre un eje de longitud total L_total = 200 mm, pero la sección cónica solo mide l = 80 mm. Si la diferencia entre el diámetro mayor y menor de la zona cónica es de 6 mm, ¿cuánto es el desplazamiento radial que se debe aplicar al contra cabezal (contrapunta) del torno?', '["3.00 mm", "1.20 mm", "7.50 mm", "15.00 mm"]'::jsonb, 2);
  insert into banco_preguntas (tema_id, tipo, texto, opts, correcto) values (tema_0, 'mc', 'Se calcula la conicidad (K) de una pieza mediante la relación de la diferencia de diámetros respecto a su longitud (K = (D - d) / L). Si el resultado de la relación es 1:10 (0.10) y la longitud total del mecanizado es de 70 mm, ¿cuál debe ser la diferencia en milímetros entre el diámetro mayor y el menor?', '["14.0 mm", "7.0 mm", "0.7 mm", "70.0 mm"]'::jsonb, 1);
  insert into banco_preguntas (tema_id, tipo, texto, opts, correcto) values (tema_0, 'mc', 'Un plano técnico especifica que una pieza cónica tiene un ángulo de inclinación del carro orientable de alfa = 3°. ¿A cuánto equivale este ángulo expresado en minutos de grado sexagesimal?', '["180''", "300''", "45''", "0.05''"]'::jsonb, 2);
  insert into banco_preguntas (tema_id, tipo, texto, opts, correcto) values (tema_0, 'mc', 'Se requiere verificar el ángulo total de conicidad de una pieza con forma de tronco de cono. Si el ángulo medido con el goniómetro respecto al eje central (semiángulo) es de 5°30'', ¿cuál es el ángulo de conicidad completo o de convergencia de la pieza?', '["10° 30''", "5° 60''", "11° 00''", "22° 00''"]'::jsonb, 2);
  insert into banco_preguntas (tema_id, tipo, texto, opts, correcto) values (tema_1, 'mc', 'Para una rosca métrica normalizada M16 x 2, ¿cuál es el diámetro de la broca que se debe utilizar para realizar el agujero previo antes de pasar el macho de roscar?', '["15.0 mm", "14.0 mm", "14.5 mm", "12.0 mm"]'::jsonb, 1);
  insert into banco_preguntas (tema_id, tipo, texto, opts, correcto) values (tema_1, 'mc', '¿Cuál es la principal característica geométrica que diferencia a una rosca Whitworth de una rosca Métrica (ISO)?', '["La rosca Whitworth se mide siempre en milímetros y la Métrica en pulgadas.", "La rosca Whitworth tiene un ángulo de flanco de 55° y crestas/fondos redondeados, mientras que la Métrica tiene un ángulo de 60° y crestas planas.", "La rosca Whitworth se utiliza para transmisión pesada por su ángulo de 29°.", "No existe diferencia geométrica; solo cambia la región de fabricación."]'::jsonb, 1);
  insert into banco_preguntas (tema_id, tipo, texto, opts, correcto) values (tema_1, 'mc', 'En la designación de una rosca unificada americana 1/2" - 13 UNC, ¿qué significa específicamente el número 13?', '["El paso de la rosca expresado directamente en milímetros.", "La dureza superficial requerida para el material del espárrago.", "La cantidad de hilos o filetes que contiene la rosca en una pulgada.", "El diámetro interno del núcleo del tornillo medido en hilos totales."]'::jsonb, 2);
  insert into banco_preguntas (tema_id, tipo, texto, opts, correcto) values (tema_1, 'mc', 'Al realizar el cálculo matemático para una rosca trapecial ACME, ¿cuál es el ángulo de flanco característico de su perfil que debe considerarse para afilar la herramienta de corte?', '["30°", "60°", "29°", "45°"]'::jsonb, 2);
  insert into banco_preguntas (tema_id, tipo, texto, opts, correcto) values (tema_1, 'mc', 'Calcula el paso (P) en milímetros de una rosca unificada americana que tiene una especificación de 20 hilos por pulgada (TPI).', '["1.27 mm", "2.00 mm", "0.78 mm", "2.54 mm"]'::jsonb, 0);
  insert into banco_preguntas (tema_id, tipo, texto, opts, correcto) values (tema_1, 'mc', '¿Cuál es el paso geométrico real (P) de un tornillo designado en un plano como M10 de rosca métrica estándar corriente (basta por defecto)?', '["1.50 mm", "1.25 mm", "1.00 mm", "2.00 mm"]'::jsonb, 1);
  insert into banco_preguntas (tema_id, tipo, texto, opts, correcto) values (tema_1, 'mc', 'Se requiere calcular la profundidad del filete (h) para una rosca métrica ISO externa (tornillo) si se conoce que su paso es P = 1.25 mm. Sabiendo que la fórmula teórica de contacto es h = 0.6134 x P, determine este valor.', '["1.250 mm", "0.767 mm", "0.541 mm", "0.866 mm"]'::jsonb, 1);
  insert into banco_preguntas (tema_id, tipo, texto, opts, correcto) values (tema_1, 'mc', 'Tienes un plano con una rosca designada como 3/8" - 16 UNF. Al revisar tus tablas técnicas de taller notas algo extraño. ¿Por qué esta designación es técnicamente incorrecta?', '["Porque 16 hilos por pulgada corresponden a la serie de paso grueso (UNC) para el diámetro de 3/8\", no a la serie de paso fino (UNF).", "Porque el diámetro de 3/8\" no puede combinarse jamás con números pares.", "Porque la nomenclatura UNF no acepta dimensiones expresadas en fracciones.", "Porque el paso debería estar dado con un punto decimal en milímetros."]'::jsonb, 0);
  insert into banco_preguntas (tema_id, tipo, texto, opts, correcto) values (tema_1, 'mc', 'Deseas verificar el paso de una rosca Whitworth con hilos muy desgastados empleando un calibrador de hilos (cuentahílos). Si cuentas exactamente 11 hilos contenidos en una sección medida de 1 pulgada, ¿cuál es el paso (P) de esta rosca en el sistema inglés?', '["11/25.4 pulgadas", "0.110 pulgadas", "1/11 de pulgada", "11 pulgadas"]'::jsonb, 2);
  insert into banco_preguntas (tema_id, tipo, texto, opts, correcto) values (tema_1, 'mc', 'Para realizar el cálculo de roscas tipo gas no selladas conocidas en el taller mecánico como BSP (British Standard Pipe), ¿qué ángulo de perfil de hilo debes considerar?', '["55°", "60°", "30°", "45°"]'::jsonb, 0);
  insert into banco_preguntas (tema_id, tipo, texto, opts, correcto) values (tema_1, 'mc', 'En el taller te entregan un tornillo marcado con la especificación M8 x 1. ¿Qué tipo de rosca representa esta nomenclatura en comparación con el estándar común?', '["Una rosca métrica de paso grueso por defecto.", "Una rosca métrica de paso fino.", "Un tornillo de paso especial con hilos cuadrados izquierdos.", "Una rosca unificada expresada en pulgadas equivalentes."]'::jsonb, 1);
  insert into banco_preguntas (tema_id, tipo, texto, opts, correcto) values (tema_1, 'mc', 'Se desea maquinar una tuerca con rosca métrica gruesa M20. Sabiendo que el paso estándar para M20 es P = 2.5 mm, ¿qué diámetro de broca debemos elegir para barrenar el agujero previo?', '["17.5 mm", "19.0 mm", "15.0 mm", "22.5 mm"]'::jsonb, 0);
  insert into banco_preguntas (tema_id, tipo, texto, opts, correcto) values (tema_1, 'mc', 'Deseas fabricar un tornillo especial con rosca Whitworth de diámetro nominal 1". Al consultar las tablas de normalización mecánica, se indica que esta rosca posee 8 hilos por pulgada. ¿Cuál es el paso aproximado expresado en milímetros?', '["8.000 mm", "3.175 mm", "1.500 mm", "2.540 mm"]'::jsonb, 1);
  insert into banco_preguntas (tema_id, tipo, texto, opts, correcto) values (tema_1, 'mc', 'Calcula el diámetro exterior nominal de un tornillo de rosca métrica fina designado como M12 x 1.25.', '["10.75 mm", "13.25 mm", "12.00 mm", "1.25 mm"]'::jsonb, 2);
  insert into banco_preguntas (tema_id, tipo, texto, opts, correcto) values (tema_1, 'mc', '¿Cuál es el ángulo incluido total del perfil de filete para cualquier rosca unificada americana de las series UNC y UNF?', '["55°", "60°", "29°", "90°"]'::jsonb, 1);
  insert into banco_preguntas (tema_id, tipo, texto, opts, correcto) values (tema_1, 'mc', 'Se requiere determinar el paso (P) de una rosca métrica si la altura teórica del triángulo fundamental sin truncar es H = 1.732 mm. Sabiendo que la relación establece que H = 0.866 x P, despeje y calcule el paso.', '["2.00 mm", "1.50 mm", "3.46 mm", "1.00 mm"]'::jsonb, 0);
  insert into banco_preguntas (tema_id, tipo, texto, opts, correcto) values (tema_1, 'mc', 'En la designación americana para tornillos delgados mediante números calibrados, un tornillo común es el N° 10 - 24 UNC. ¿Qué propiedad geométrica define principalmente el número 10?', '["Un código de tamaño que representa un diámetro exterior nominal específico menor a un cuarto de pulgada.", "La longitud total del cuerpo del espárrago expresada en octavos de pulgada.", "El paso exacto de la rosca medido de forma directa en milésimas de pulgada.", "El número de ranuras de lubricación que debe llevar la cabeza del tornillo."]'::jsonb, 0);
  insert into banco_preguntas (tema_id, tipo, texto, opts, correcto) values (tema_2, 'mc', 'Se va a desbastar una barra de acero de diámetro D = 2 pulgadas en el torno. Si el manual sugiere una velocidad de corte (Vc) de 90 pies/min, ¿a cuántas RPM se debe configurar la máquina?', '["720 RPM", "180 RPM", "572 RPM", "90 RPM"]'::jsonb, 1);
  insert into banco_preguntas (tema_id, tipo, texto, opts, correcto) values (tema_2, 'mc', 'Se requiere calcular las RPM para tornear un eje de aluminio de D = 40 mm de diámetro. La velocidad de corte recomendada para el acabado es Vc = 150 m/min. Calcule las revoluciones por minuto necesarias empleando la fórmula métrica.', '["3750 RPM", "1194 RPM", "377 RPM", "1500 RPM"]'::jsonb, 1);
  insert into banco_preguntas (tema_id, tipo, texto, opts, correcto) values (tema_2, 'mc', 'En una fresadora vertical, se va a utilizar una fresa de carburo de 12 mm de diámetro. La velocidad de corte recomendada es Vc = 80 m/min. ¿A cuántas revoluciones por minuto se debe programar el husillo?', '["2122 RPM", "6666 RPM", "960 RPM", "530 RPM"]'::jsonb, 0);
  insert into banco_preguntas (tema_id, tipo, texto, opts, correcto) values (tema_2, 'mc', 'Un husillo de torno gira a 450 RPM mientras cilindras un eje de latón. Si el operario decide duplicar el diámetro de la barra a trabajar pero mantener la misma velocidad de corte (Vc), ¿cómo deben alterarse las RPM?', '["Se deben duplicar las RPM (900 RPM).", "Deben mantenerse iguales en 450 RPM.", "Se deben reducir las RPM a la mitad (225 RPM).", "Se deben elevar al cuadrado las RPM originales."]'::jsonb, 2);
  insert into banco_preguntas (tema_id, tipo, texto, opts, correcto) values (tema_2, 'mc', 'Se requiere tornear un eje a un diámetro final de 38 mm. La lectura actual indica que la pieza está en 39.4 mm. ¿Qué profundidad de pasada (ap) radial debes aplicar en el carro transversal para alcanzar la medida en un solo corte?', '["1.40 mm", "0.70 mm", "0.35 mm", "2.80 mm"]'::jsonb, 1);
  insert into banco_preguntas (tema_id, tipo, texto, opts, correcto) values (tema_2, 'mc', 'Calcule la velocidad de corte (Vc) en metros por minuto que se está aplicando si un eje de D = 50 mm de diámetro gira en el torno a N = 600 RPM.', '["30.00 m/min", "94.24 m/min", "94248 m/min", "235.60 m/min"]'::jsonb, 1);
  insert into banco_preguntas (tema_id, tipo, texto, opts, correcto) values (tema_2, 'mc', 'Una broca de acero de alta velocidad (HSS) de 1/2 pulgada requiere una velocidad de corte de 80 pies/min. Calcule las RPM requeridas.', '["640 RPM", "160 RPM", "320 RPM", "1280 RPM"]'::jsonb, 2);
  insert into banco_preguntas (tema_id, tipo, texto, opts, correcto) values (tema_2, 'mc', 'Se va a desbastar un eje de acero inoxidable de diámetro D = 80 mm con un inserto de carburo. La velocidad de corte recomendada es Vc = 180 m/min. Calcule las RPM óptimas.', '["2250 RPM", "1432 RPM", "716 RPM", "180 RPM"]'::jsonb, 2);
  insert into banco_preguntas (tema_id, tipo, texto, opts, correcto) values (tema_3, 'mc', 'Un plano técnico muestra una pieza mecanizada con una longitud de 4.75 pulgadas. ¿Cuál es el equivalente de esta medida en milímetros?', '["118.75 mm", "12.06 mm", "120.65 mm", "19.00 mm"]'::jsonb, 2);
  insert into banco_preguntas (tema_id, tipo, texto, opts, correcto) values (tema_3, 'mc', 'Si el calibrador de un operador marca una lectura de 0.035 pulgadas, ¿cuál es su equivalente aproximado en fracciones comunes de pulgada utilizadas en el taller?', '["1/32\"", "1/16\"", "1/64\"", "3/64\""]'::jsonb, 2);
  insert into banco_preguntas (tema_id, tipo, texto, opts, correcto) values (tema_3, 'mc', 'Tienes un micrómetro en milímetros y la hoja de procesos exige desbastar un eje hasta un diámetro exterior de 0.875 pulgadas. ¿Qué lectura debes buscar en tu instrumento métrico?', '["25.400 mm", "22.225 mm", "21.875 mm", "18.500 mm"]'::jsonb, 1);
  insert into banco_preguntas (tema_id, tipo, texto, opts, correcto) values (tema_3, 'mc', 'Un calibrador para verificar longitudes tiene una tolerancia límite grabada de 1.125". Si requieres verificar esta dimensión usando bloques patrón métricos, ¿qué medida exacta debes conformar?', '["25.525 mm", "28.575 mm", "28.125 mm", "27.000 mm"]'::jsonb, 1);
  insert into banco_preguntas (tema_id, tipo, texto, opts, correcto) values (tema_3, 'mc', '¿A cuántas pulgadas decimales equivale una medida estándar de un cuarto de pulgada (1/4") grabada comúnmente en las herramientas?', '["0.250\"", "0.125\"", "0.400\"", "0.025\""]'::jsonb, 0);
  insert into banco_preguntas (tema_id, tipo, texto, opts, correcto) values (tema_3, 'mc', 'Un plano solicita un chavetero con una profundidad de 5/16 de pulgada. ¿A cuántos milímetros equivale esta profundidad si ajustas el cero de tu máquina con un indicador digital en milímetros?', '["5.160 mm", "4.062 mm", "7.937 mm", "0.312 mm"]'::jsonb, 2);
  insert into banco_preguntas (tema_id, tipo, texto, opts, correcto) values (tema_3, 'mc', 'Un nonio de un vernier en pulgadas divide una longitud de 0.050 pulgadas en 25 partes iguales. ¿Cuál es la resolución o lectura mínima que puede registrar este instrumento?', '["0.002\"", "0.001\"", "0.020\"", "0.005\""]'::jsonb, 0);
  insert into banco_preguntas (tema_id, tipo, texto, opts, correcto) values (tema_3, 'mc', 'Un husillo CNC opera bajo el sistema inglés y avanza a 15 pulgadas/minuto. Si configuras la pantalla en sistema métrico, ¿qué valor equivalente en milímetros por minuto debe mostrar?', '["150.0 mm/min", "381.0 mm/min", "590.5 mm/min", "38.10 mm/min"]'::jsonb, 1);
  insert into banco_preguntas (tema_id, tipo, texto, opts, correcto) values (tema_3, 'mc', 'Se mecaniza una polea y el plano marca un diámetro de 1 pulgada y 3/4. ¿Cuál es el equivalente decimal en pulgadas de esta medida mixta?', '["1.340\"", "1.750\"", "1.375\"", "1.600\""]'::jsonb, 1);
  insert into banco_preguntas (tema_id, tipo, texto, opts, correcto) values (tema_3, 'mc', 'Una pieza cilíndrica de 3 pulgadas de diámetro debe reducirse a 2.625 pulgadas. ¿Cuánto material en total se debe remover medido directamente sobre el diámetro exterior?', '["0.375\"", "0.187\"", "0.625\"", "1.375\""]'::jsonb, 0);
end $$;